name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate circuits and verifier
        run: |
          mkdir -p circuits/semaphore/build
          # Add commands to generate circuit.json, proving_key.bin, verification_key.json, and verifier.sol
          # Example:
          # npx circom circuits/semaphore/circuit.circom --r1cs --wasm --sym --c
          # npx snarkjs setup --protocol groth16 circuits/semaphore/circuit.r1cs circuits/semaphore/proving_key.bin circuits/semaphore/verification_key.json
          # npx snarkjs zkey export solidityverifier circuits/semaphore/proving_key.bin circuits/semaphore/verifier.sol

      - name: Access proving_key.bin secret
        run: echo "${{ secrets.PROVING_KEY_BIN }}" > circuits/semaphore/build/proving_key.bin

      - name: Run tests
        run: npx hardhat test
